import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Indigo-Slate design system tokens (from design files)
        tertiary: '#453d36',
        'on-error-container': '#93000a',
        'on-surface': '#191c1e',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#bec6df',
        'surface-bright': '#f7f9fb',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3e465b',
        'primary-fixed': '#dae2fc',
        'on-secondary-fixed-variant': '#3e465c',
        'secondary-fixed': '#dae2fd',
        'surface-container-low': '#f2f4f6',
        'on-primary': '#ffffff',
        primary: '#363e52',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#565e73',
        'on-tertiary-fixed-variant': '#4e453e',
        'on-secondary-container': '#5c647b',
        'inverse-surface': '#2d3133',
        'tertiary-fixed': '#eee0d7',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-container': '#d6c9bf',
        surface: '#f7f9fb',
        background: '#f7f9fb',
        'on-tertiary-fixed': '#211a15',
        'on-background': '#191c1e',
        'primary-container': '#4d556a',
        'on-surface-variant': '#45464c',
        'tertiary-fixed-dim': '#d1c4bb',
        'secondary-fixed-dim': '#bec6e0',
        outline: '#76777d',
        'on-error': '#ffffff',
        'surface-variant': '#e0e3e5',
        'on-primary-container': '#c2cae3',
        'tertiary-container': '#5d544d',
        'surface-container': '#eceef0',
        'surface-container-highest': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        'on-secondary-fixed': '#131b2e',
        'surface-dim': '#d8dadc',
        secondary: '#565e74',
        'secondary-container': '#dae2fd',
        'primary-fixed-dim': '#bec6df',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #4d556a 0%, #656d84 100%)',
      },
      boxShadow: {
        ambient: '0px 24px 48px rgba(77, 85, 106, 0.06)',
        'ambient-sm': '0px 8px 24px rgba(77, 85, 106, 0.06)',
      },
    },
  },
  plugins: [],
}

export default config
