import type { TDocumentDefinitions, Content, TableCell, StyleDictionary } from 'pdfmake/interfaces'
import type {
  WeeklyTeamReport,
  IndividualEmployeeReport,
  BillableHoursReport,
} from './aggregation'

// ─── Shared Styles ──────────────────────────────────────────────────────────

const STYLES: StyleDictionary = {
  header: { fontSize: 18, bold: true, color: '#1e293b', margin: [0, 0, 0, 4] },
  subHeader: { fontSize: 10, color: '#64748b', margin: [0, 0, 0, 16] },
  sectionTitle: { fontSize: 12, bold: true, color: '#334155', margin: [0, 16, 0, 8] },
  tableHeader: { fontSize: 9, bold: true, color: '#ffffff', fillColor: '#4f46e5' },
  tableCell: { fontSize: 9, color: '#334155' },
  totalRow: { fontSize: 9, bold: true, color: '#1e293b', fillColor: '#e0e7ff' },
  meta: { fontSize: 8, color: '#94a3b8' },
}

function headerBlock(title: string, meta: Record<string, string>): Content[] {
  const metaLine = Object.entries(meta).map(([k, v]) => `${k}: ${v}`).join('  |  ')
  return [
    { text: title, style: 'header' },
    { text: metaLine, style: 'subHeader' },
    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#e2e8f0' }], margin: [0, 0, 0, 12] as [number, number, number, number] },
  ]
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

// ─── Weekly Team PDF ────────────────────────────────────────────────────────

export function weeklyTeamToPDF(report: WeeklyTeamReport): TDocumentDefinitions {
  const headers: TableCell[] = [
    'Employee', 'Committed', 'Completed', 'Rate %', 'Planned Hrs', 'Actual Hrs', 'Variance', 'Overdue',
  ].map(h => ({ text: h, style: 'tableHeader' }))

  const body: TableCell[][] = [headers]
  for (const r of report.rows) {
    body.push([
      { text: r.employee_name, style: 'tableCell' },
      { text: String(r.tasks_committed), style: 'tableCell', alignment: 'center' },
      { text: String(r.tasks_completed), style: 'tableCell', alignment: 'center' },
      { text: `${r.completion_rate}%`, style: 'tableCell', alignment: 'center' },
      { text: String(r.planned_hours), style: 'tableCell', alignment: 'right' },
      { text: String(r.actual_hours), style: 'tableCell', alignment: 'right' },
      { text: String(r.hours_variance), style: 'tableCell', alignment: 'right' },
      { text: String(r.overdue_count), style: 'tableCell', alignment: 'center' },
    ])
  }
  // Totals row
  body.push([
    { text: 'TOTAL', style: 'totalRow' },
    { text: String(report.totals.tasks_committed), style: 'totalRow', alignment: 'center' },
    { text: String(report.totals.tasks_completed), style: 'totalRow', alignment: 'center' },
    { text: `${report.totals.completion_rate}%`, style: 'totalRow', alignment: 'center' },
    { text: String(report.totals.planned_hours), style: 'totalRow', alignment: 'right' },
    { text: String(report.totals.actual_hours), style: 'totalRow', alignment: 'right' },
    { text: String(Math.round((report.totals.actual_hours - report.totals.planned_hours) * 10) / 10), style: 'totalRow', alignment: 'right' },
    { text: String(report.totals.overdue_count), style: 'totalRow', alignment: 'center' },
  ])

  return {
    content: [
      ...headerBlock(`Weekly Team Performance — ${report.team_name}`, {
        'Period': `${formatDate(report.date_from)} – ${formatDate(report.date_to)}`,
        'Generated by': report.generated_by,
        'Date': formatDate(report.generated_at),
      }),
      { text: 'Performance Breakdown', style: 'sectionTitle' },
      {
        table: { headerRows: 1, widths: ['*', 50, 55, 40, 55, 55, 52, 45], body },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0,
          hLineColor: () => '#e2e8f0',
          paddingLeft: () => 6,
          paddingRight: () => 6,
          paddingTop: () => 4,
          paddingBottom: () => 4,
        },
      },
    ],
    styles: STYLES,
    defaultStyle: { font: 'Helvetica' },
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
  }
}

// ─── Individual Employee PDF ────────────────────────────────────────────────

export function individualToPDF(report: IndividualEmployeeReport): TDocumentDefinitions {
  const summaryContent: Content[] = [
    { text: 'Summary', style: 'sectionTitle' },
    {
      columns: [
        { text: `Total Tasks: ${report.summary.total_tasks}`, style: 'tableCell', width: 'auto' },
        { text: `Completed: ${report.summary.completed}`, style: 'tableCell', width: 'auto' },
        { text: `In Progress: ${report.summary.in_progress}`, style: 'tableCell', width: 'auto' },
        { text: `Overdue: ${report.summary.overdue}`, style: 'tableCell', width: 'auto' },
        { text: `On-Time Rate: ${report.summary.on_time_rate}%`, style: 'tableCell', width: 'auto' },
      ],
      columnGap: 20,
      margin: [0, 0, 0, 8] as [number, number, number, number],
    },
    {
      columns: [
        { text: `Est. Hours: ${report.summary.total_estimated}`, style: 'tableCell', width: 'auto' },
        { text: `Actual Hours: ${report.summary.total_actual}`, style: 'tableCell', width: 'auto' },
      ],
      columnGap: 20,
      margin: [0, 0, 0, 12] as [number, number, number, number],
    },
  ]

  const headers: TableCell[] = [
    'Task', 'Project', 'Status', 'Priority', 'Est Hrs', 'Act Hrs', 'Due', 'On Time',
  ].map(h => ({ text: h, style: 'tableHeader' }))

  const body: TableCell[][] = [headers]
  for (const r of report.rows) {
    body.push([
      { text: r.task_title, style: 'tableCell' },
      { text: r.project_name, style: 'tableCell' },
      { text: r.status, style: 'tableCell' },
      { text: r.priority, style: 'tableCell' },
      { text: r.estimated_hours != null ? String(r.estimated_hours) : '—', style: 'tableCell', alignment: 'right' },
      { text: r.actual_hours != null ? String(r.actual_hours) : '—', style: 'tableCell', alignment: 'right' },
      { text: r.due_date ? formatDate(r.due_date) : '—', style: 'tableCell' },
      { text: r.on_time === null ? '—' : r.on_time ? 'Yes' : 'No', style: 'tableCell', alignment: 'center' },
    ])
  }

  return {
    content: [
      ...headerBlock(`Individual Report — ${report.employee_name}`, {
        'Period': `${formatDate(report.date_from)} – ${formatDate(report.date_to)}`,
        'Generated by': report.generated_by,
        'Date': formatDate(report.generated_at),
      }),
      ...summaryContent,
      { text: 'Task Details', style: 'sectionTitle' },
      {
        table: { headerRows: 1, widths: ['*', 80, 55, 50, 40, 40, 60, 40], body },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0,
          hLineColor: () => '#e2e8f0',
          paddingLeft: () => 6,
          paddingRight: () => 6,
          paddingTop: () => 4,
          paddingBottom: () => 4,
        },
      },
    ],
    styles: STYLES,
    defaultStyle: { font: 'Helvetica' },
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
  }
}

// ─── Billable Hours PDF ─────────────────────────────────────────────────────

export function billableToPDF(report: BillableHoursReport): TDocumentDefinitions {
  const headers: TableCell[] = [
    'Task', 'Project', 'Assignee', 'Est Hrs', 'Act Hrs', 'Status',
  ].map(h => ({ text: h, style: 'tableHeader' }))

  const body: TableCell[][] = [headers]
  for (const r of report.rows) {
    body.push([
      { text: r.task_title, style: 'tableCell' },
      { text: r.project_name, style: 'tableCell' },
      { text: r.assignee_name, style: 'tableCell' },
      { text: r.estimated_hours != null ? String(r.estimated_hours) : '—', style: 'tableCell', alignment: 'right' },
      { text: r.actual_hours != null ? String(r.actual_hours) : '—', style: 'tableCell', alignment: 'right' },
      { text: r.status, style: 'tableCell' },
    ])
  }
  body.push([
    { text: 'TOTAL', style: 'totalRow' },
    { text: `${report.totals.total_tasks} tasks`, style: 'totalRow' },
    { text: `${report.totals.completed} done`, style: 'totalRow' },
    { text: String(report.totals.total_estimated), style: 'totalRow', alignment: 'right' },
    { text: String(report.totals.total_actual), style: 'totalRow', alignment: 'right' },
    { text: '', style: 'totalRow' },
  ])

  return {
    content: [
      ...headerBlock('Billable Hours Summary', {
        'Period': `${formatDate(report.date_from)} – ${formatDate(report.date_to)}`,
        'Generated by': report.generated_by,
        'Date': formatDate(report.generated_at),
      }),
      { text: 'Billable Tasks', style: 'sectionTitle' },
      {
        table: { headerRows: 1, widths: ['*', 80, 80, 50, 50, 55], body },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0,
          hLineColor: () => '#e2e8f0',
          paddingLeft: () => 6,
          paddingRight: () => 6,
          paddingTop: () => 4,
          paddingBottom: () => 4,
        },
      },
    ],
    styles: STYLES,
    defaultStyle: { font: 'Helvetica' },
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
  }
}

// ─── Render to Uint8Array ────────────────────────────────────────────────────

export async function renderPDF(docDef: TDocumentDefinitions): Promise<Uint8Array> {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const pdfmake = require('pdfmake')

  const fonts = {
    Helvetica: {
      normal: 'Helvetica',
      bold: 'Helvetica-Bold',
      italics: 'Helvetica-Oblique',
      bolditalics: 'Helvetica-BoldOblique',
    },
  }

  const printer = new pdfmake(fonts)
  const doc = printer.createPdfKitDocument(docDef)
  const chunks: Buffer[] = []

  return new Promise<Uint8Array>((resolve, reject) => {
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => {
      const buf = Buffer.concat(chunks)
      resolve(new Uint8Array(buf))
    })
    doc.on('error', (err: Error) => reject(err))
    doc.end()
  })
}
